# Generated by Django 4.2.8 on 2024-01-06 01:41

import backend.models.order
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ref_no', models.CharField(default=backend.models.order.generate_reference_number, editable=False, max_length=10, unique=True)),
                ('date_ordered', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('to-pay', 'To Pay'), ('to-ship', 'To Ship'), ('to-recieve', 'To Recieve'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='to-pay', max_length=12)),
                ('payment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.paymentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.uniform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('to-pay', 'To Pay'), ('to-ship', 'To Ship'), ('to-recieve', 'To Recieve'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='to-pay', max_length=12)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_order_history', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
