# Generated by Django 4.2.8 on 2024-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentoption',
            name='is_facilitated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentoption',
            name='receipt_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
