# Generated by Django 4.1.5 on 2023-11-26 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_uniformimage_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformimage',
            name='uniform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.uniform'),
        ),
    ]
