# Generated by Django 4.2.8 on 2024-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('meter', 'Meter')], default='piece', max_length=15),
        ),
    ]
