# Generated by Django 4.2.8 on 2024-01-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_paymentoption_is_facilitated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniform',
            name='barcode',
        ),
    ]
