# Generated by Django 4.2.8 on 2024-01-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_uniform_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('to-pay', 'To Pay'), ('to-prepare', 'To Prepare'), ('to-recieve', 'To Recieve'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='to-pay', max_length=12),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(choices=[('to-pay', 'To Pay'), ('to-prepare', 'To Prepare'), ('to-recieve', 'To Recieve'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='to-pay', max_length=12),
        ),
    ]
