# Generated by Django 4.2.8 on 2024-01-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_order_date_ordered_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
