# Generated by Django 4.2.8 on 2024-02-23 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_inventory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uniforms', to='backend.department'),
        ),
    ]
