# Generated by Django 4.2.8 on 2023-12-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
