# Generated by Django 4.2.8 on 2024-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_order_status_alter_orderhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='status',
            field=models.CharField(choices=[('in-stock', 'In-Stock'), ('out-of-stock', 'Out-of-Stock'), ('draft', 'Draft')], default='in-stock', max_length=15),
        ),
    ]
