# Generated by Django 4.2.8 on 2024-02-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger')], default='others', max_length=8)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unseen', 'Unseen'), ('seen', 'Seen')], default='unseen', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
