# Generated by Django 4.2.8 on 2023-12-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('on-cart', 'On-Cart'), ('purchased', 'Purchased'), ('deleted', 'Deleted')], default='on-cart', max_length=12),
        ),
    ]
