# Generated by Django 4.2.8 on 2024-01-02 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_paymentoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentoption',
            old_name='abbreviation',
            new_name='code',
        ),
    ]
