# Generated by Django 4.2.8 on 2024-03-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_expense_billing_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='uniform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='backend.uniform'),
        ),
    ]
