# Generated by Django 4.2.8 on 2024-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_abbreviation_paymentoption_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentoption',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
