# Generated by Django 4.2.8 on 2024-05-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_orderitem_uniform'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='capital_type',
            field=models.CharField(blank=True, choices=[('cloth_capital', 'Cloth Capital'), ('departmental_uniform_capital', 'Departmental Uniform Capital')], max_length=50, null=True),
        ),
    ]
