# Generated by Django 4.2.8 on 2024-01-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_paymentoption_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniform',
            name='allow_pre_order',
        ),
    ]
