# Generated by Django 4.2.8 on 2024-05-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_expense_capital_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='billing_month',
            new_name='billing_date',
        ),
    ]
