# Generated by Django 4.2.8 on 2024-05-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_billing_month_expense_billing_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uniform',
            old_name='variants',
            new_name='variant',
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('uniform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='backend.uniform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
