# Generated by Django 4.2.8 on 2024-05-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_variants_uniform_variant_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniform',
            name='variant',
        ),
        migrations.AddField(
            model_name='uniform',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('meter', 'Meter')], default='piece', max_length=15),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(default='DEFAULT', max_length=255),
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
